version: "3" 
services:
  web_secondblogwsl:
    image: alexrogna/secondblogwsl_web:prod
    expose:
      - 3000
    env_file:
      - .env/production/database_secondblogwsl
      - .env/production/web_secondblogwsl
    environment:
      - VIRTUAL_HOST=secondblogwsl.alexrogna.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=secondblogwsl.alexrogna.com
    restart: always

  database_secondblogwsl:
    image: postgres
    env_file:
      - .env/production/database_secondblogwsl
    volumes:
      - db_data_secondblogwsl:/var/lib/postgresql/data
    restart: always
    
  db-migrator_secondblogwsl:
    image: alexrogna/secondblogwsl_web:prod
    command: ["./wait-for", "--timeout=300", "database_secondblogwsl:5432", "--", "bin/rails", "db:create" , "db:migrate"]
    env_file:
      - .env/production/database_secondblogwsl
      - .env/production/web_secondblogwsl
volumes:
  db_data_secondblogwsl: