version: "3"
services:
  web_secondblogwsl:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    ports:
      - "3003:3000"
    volumes: 
      - ./secondblogwsl:/opt/app
      - gem_cache_secondblogwsl:/gems
    env_file: 
      - .env/development/database_secondblogwsl
      - .env/development/web_secondblogwsl
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=webpack_dev_server_secondblogwsl
  webpack_dev_server_secondblogwsl:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: ./bin/webpack-dev-server
    ports: 
      - "3038:3038"
    volumes: 
      - ./secondblogwsl:/opt/app
      - gem_cache_secondblogwsl:/gems
    env_file: 
      - .env/development/database_secondblogwsl
      - .env/development/web_secondblogwsl
    environment: 
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
  database_secondblogwsl:
    image: postgres
    env_file: 
      - .env/development/database_secondblogwsl
    volumes: 
      - db_data_secondblogwsl:/var/lib/postgresql/data
volumes: 
  db_data_secondblogwsl:
  gem_cache_secondblogwsl: